### PR TITLE
Bring versions current

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@paulbygrave please review

**Comment by paulbygrave** [comment]
@gliptak You also need to update the Makefile within this repo, otherwise the new container won't be built and pushed correctly. Happy to do it, or leave to you if you'd like to try it yourself?

**Comment by gliptak** [comment]
@paulbygrave thank you for the pointer. Update `Makefile`

PS Maybe one of those version numbers are to be removed?

**Comment by paulbygrave** [comment]
@gliptak There's probably a better way to do it (if this were GitLab I'd just declare a single project variable) but not sure myself how to do that neatly in GitHub. I'll just update the README for future people who may want to update this,

**Pull request merged**
